stages:
  - deploy

deploy-be:
  stage: deploy
  script:
    - cd IzvorniKod/backend;
      git config --global user.email "$blank";
      git config --global user.name "blank";
      git init;
      git add .;
      git commit -m "heroku deploy";
      git push -f https://blank:26b20b3a-3bd5-4dd1-9ae3-52aaa714382a@git.heroku.com/halo112h.git HEAD:master
  only:
    refs:
      - master
    changes:
      - backend/**

deploy-fe:
  stage: deploy
  script:
    - cd IzvorniKod/frontend;
      git config --global user.email "blank";
      git config --global user.name "blank";
      git init;
      git add .;
      git commit -m "heroku deploy";
      git push -f https://blank:26b20b3a-3bd5-4dd1-9ae3-52aaa714382a@git.heroku.com/halo112c.git HEAD:master
  only:
    refs:
      - master
    changes:
      - frontend/**
